# Generated by Django 4.2.20 on 2025-03-19 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название издательства')),
                ('description', models.TextField(blank=True, verbose_name='Описание издательства')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL логотипа')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание книги')),
                ('cover_url', models.URLField(blank=True, verbose_name='URL обложки')),
                ('book_url', models.URLField(verbose_name='URL книги на сайте издательства')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления в систему')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.publisher', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['-publication_date'], name='books_book_publica_0f612f_idx'), models.Index(fields=['publisher', '-publication_date'], name='books_book_publish_509e24_idx')],
            },
        ),
    ]
